CREATE TABLE PRODUCT_MASTER (
  PRODUCT_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_NAME 		VARCHAR(100) 	NOT NULL,
  CREATED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY 		VARCHAR(20)
);

CREATE TABLE PRODUCT_INVENTORY(
  PRODUCT_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  MAX_CAPACITY   	INT 	NOT NULL,
  AVAILABLE_STOCK 	INT 	NOT NULL,
  REFILL_PERCENTAGE INT 	NOT NULL
);

CREATE TABLE PRODUCT_PURCHASE_HISTORY(
  PRODUCT_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  PURCHASE_AMOUNT 	VARCHAR(100) 	NOT NULL,
  PURCHASED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  PURCHASED_BY 		VARCHAR(20)
);

CREATE TABLE PRODUCT_REFILL_HISTORY(
  PRODUCT_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  REFILL_AMOUNT 	VARCHAR(100) 	NOT NULL,
  REFILLED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  REFILLED_BY 		VARCHAR(20)
);