CREATE TABLE PRODUCT_MASTER (
  PRODUCT_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_NAME 		VARCHAR(100) 	NOT NULL,
  CREATED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY 		VARCHAR(20)
);

CREATE TABLE PRODUCT_INVENTORY(
  INV_ID 	        INT  AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID        INT     NOT NULL,
  MAX_CAPACITY   	INT 	NOT NULL,
  AVAILABLE_STOCK 	INT 	NOT NULL,
  REFILL_PERCENTAGE INT 	NOT NULL,

  FOREIGN KEY (PRODUCT_ID) 	REFERENCES 	PRODUCT_MASTER(PRODUCT_ID)
);

CREATE TABLE PRODUCT_PURCHASE_HISTORY(
  PURC_ID 	        INT  AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID        INT     NOT NULL,
  PURCHASE_AMOUNT 	INT 	NOT NULL,
  PURCHASED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  PURCHASED_BY 		VARCHAR(20),

  FOREIGN KEY (PRODUCT_ID) 	REFERENCES 	PRODUCT_MASTER(PRODUCT_ID)
);

CREATE TABLE PRODUCT_REFILL_HISTORY(
  REFILL_ID 	    INT  AUTO_INCREMENT PRIMARY KEY,
  PRODUCT_ID        INT     NOT NULL,
  REFILL_AMOUNT 	INT 	NOT NULL,
  REFILLED_AT 		TIMESTAMP 		DEFAULT CURRENT_TIMESTAMP,
  REFILLED_BY 		VARCHAR(20),

  FOREIGN KEY (PRODUCT_ID) 	REFERENCES 	PRODUCT_MASTER(PRODUCT_ID)
);