INSERT INTO PRODUCT_MASTER VALUES (1, 'Cookies', CURRENT_TIMESTAMP, 'system');
INSERT INTO PRODUCT_MASTER VALUES (2, 'Cake', CURRENT_TIMESTAMP, 'system');
INSERT INTO PRODUCT_MASTER VALUES (3, 'Juice', CURRENT_TIMESTAMP, 'system');

INSERT INTO PRODUCT_INVENTORY VALUES (1, 1, 20, 15, 10);
INSERT INTO PRODUCT_INVENTORY VALUES (2, 2, 15, 10, 5);
INSERT INTO PRODUCT_INVENTORY VALUES (3, 3, 40, 30, 15);