server:
  port: 9095

spring:
  application:
    name: vending-machine

  security:
    user:
      name: user
      password: user
      roles: admin

  h2:
    console:
      enabled: true

  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false


  flyway:
    enabled: true
    url: jdbc:h2:mem:testdb
    user: sa
    password:
    baseline-on-migrate: true
    locations: classpath:db/migration

